// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node --experimental-strip-types prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "",
    // Dev-only. The real DATABASE_URL points at a database literally named
    // "template1" (an artifact of how `prisma dev`'s local proxy names its
    // default DB). Postgres's CREATE DATABASE clones from template1 by
    // default cluster-wide, so `migrate dev`'s auto-created shadow database
    // silently inherited the app's full schema instead of being empty,
    // breaking migration replay ("type already exists"). Fixed by pointing
    // shadowDatabaseUrl at a database explicitly created with `TEMPLATE
    // template0` (Postgres's pristine, never-modified template) — dev-only,
    // irrelevant to `migrate deploy` in production. Omitted entirely (not
    // set to "") when SHADOW_DATABASE_URL is absent — `migrate deploy`
    // doesn't use a shadow database at all, but Prisma 7's config loader
    // still validates shadowDatabaseUrl if the key is present, and rejects
    // an empty string ("must not be an empty string"), which broke the
    // production build the moment `prisma migrate deploy` was added there.
    ...(process.env["SHADOW_DATABASE_URL"] ? { shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"] } : {}),
  },
});
