/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Projects
     * @description Entity/role-scoped project listing. Roles: all authenticated realms.
     */
    get: operations["listProjects"];
    put?: never;
    /**
     * Create Project
     * @description Domain Model CreateProject command. Roles: pm, platform_admin.
     */
    post: operations["createProject"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{projectId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Project detail
     * @description RLS-scoped project detail. Roles: all authenticated realms.
     */
    get: operations["getProject"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Project fields
     * @description Update mutable Project fields. Roles: pm, platform_admin.
     */
    patch: operations["updateProject"];
    trace?: never;
  };
  "/projects/{projectId}/phases": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add Phase
     * @description Add a Phase to a Project. Roles: pm.
     */
    post: operations["addProjectPhase"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{projectId}/milestones": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add Milestone
     * @description Add a Milestone to a Project. Roles: pm.
     */
    post: operations["addProjectMilestone"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{projectId}/milestones/{milestoneId}:mark-client-visible": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mark Milestone Client Visible
     * @description Apply CanMarkMilestoneClientVisibleSpecification. Roles: pm.
     */
    post: operations["markMilestoneClientVisible"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{projectId}/boq": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get active BOQ summary
     * @description Get active BOQ summary. Roles: architect, pm, finance, executive.
     */
    get: operations["getProjectBoq"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/boq/{boqId}/revisions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create new Draft revision
     * @description Create new Draft revision. Roles: pm, finance.
     */
    post: operations["createBoqRevision"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/boq/{boqId}/revisions/{revisionId}/line-items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List line items
     * @description Paginated line item listing. RLS-scoped; vendor sees only assigned lines.
     */
    get: operations["listBoqLineItems"];
    put?: never;
    /**
     * Add line item
     * @description Add line item. Roles: pm, finance.
     */
    post: operations["addBoqLineItem"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/boq/{boqId}/revisions/{revisionId}:submit-for-approval": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit BOQ revision for approval
     * @description Transition draft to pending_approval. Roles: pm.
     */
    post: operations["submitBoqRevisionForApproval"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/boq/{boqId}/revisions/{revisionId}:approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Approve BOQ revision
     * @description Transition to approved and trigger BoqRevisionApproved event. Roles: finance, pm.
     */
    post: operations["approveBoqRevision"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/boq/{boqId}/revisions/{revisionId}:export-pdf": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Export BOQ revision PDF
     * @description Generate bilingual Arabic-typography-correct PDF through Export Adapter.
     */
    post: operations["exportBoqRevisionPdf"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{projectId}/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create DocumentPackage
     * @description Create DocumentPackage. Roles: architect, pm.
     */
    post: operations["createDocumentPackage"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/documents/{packageId}/versions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List versions
     * @description RLS-scoped version listing; client sees current approved and shared version only.
     */
    get: operations["listDocumentVersions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/documents/{packageId}/versions:initiate-upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Begin upload
     * @description Start the two-step signed URL upload flow. Roles: architect, pm.
     */
    post: operations["initiateDocumentVersionUpload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/documents/{packageId}/versions/{versionId}:complete-upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Complete upload
     * @description Verify uploaded object exists and transition version to draft.
     */
    post: operations["completeDocumentVersionUpload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/documents/{packageId}/versions/{versionId}:submit-for-review": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit DocumentVersion for review
     * @description Transition draft to for_review. Roles: architect.
     */
    post: operations["submitDocumentVersionForReview"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/documents/{packageId}/versions/{versionId}:approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Approve DocumentVersion
     * @description Transition for_review to approved and trigger supersession. Roles: pm.
     */
    post: operations["approveDocumentVersion"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/documents/{packageId}/versions/{versionId}:export-pdf": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Export DocumentVersion PDF
     * @description Generate print-ready Arabic-typography-correct PDF through Export Adapter.
     */
    post: operations["exportDocumentVersionPdf"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/documents/{packageId}/versions/{versionId}:download-url": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get document version download URL
     * @description Return short-lived signed URL after authorization.
     */
    get: operations["getDocumentVersionDownloadUrl"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Users
     * @description Entity-scoped user listing. Roles: platform_admin, pm project-scoped subset.
     */
    get: operations["listUsers"];
    put?: never;
    /**
     * Provision a User
     * @description Provision a User. Roles: platform_admin.
     */
    post: operations["provisionUser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update User
     * @description Update User fields, including preferredLocale. Roles: self or platform_admin.
     */
    patch: operations["updateUser"];
    trace?: never;
  };
  "/roles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List available Roles
     * @description List available Roles. Roles: platform_admin.
     */
    get: operations["listRoles"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{userId}/role-assignments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Assign Role
     * @description Assign Role. Roles: platform_admin.
     */
    post: operations["assignUserRole"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{userId}/role-assignments/{assignmentId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Revoke assignment
     * @description Revoke assignment by setting revoked_at. Roles: platform_admin.
     */
    delete: operations["revokeUserRoleAssignment"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/entities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Entities
     * @description List Entities. Roles: platform_admin, executive read.
     */
    get: operations["listEntities"];
    put?: never;
    /**
     * Provision new Entity
     * @description Provision new Entity through EntityProvisioningService. Roles: platform_admin.
     */
    post: operations["provisionEntity"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/entities/{entityId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Entity configuration
     * @description Update Entity configuration, including optional boqVarianceThresholdPercent. Roles: platform_admin.
     */
    patch: operations["updateEntity"];
    trace?: never;
  };
  "/projects/{projectId}:reassign-entity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reassign Project Entity
     * @description ChangeProjectEntity command. Roles: platform_admin only.
     */
    post: operations["reassignProjectEntity"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/dashboard/portfolio": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Portfolio rollup
     * @description Portfolio rollup backed by reporting.mvw_portfolio_rollup. Roles: executive, pm own projects.
     */
    get: operations["getPortfolioDashboard"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/notifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List notifications
     * @description List in-app notifications for the authenticated user.
     */
    get: operations["listNotifications"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/notifications/{id}:mark-read": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mark notification as read
     * @description Mark as read. RLS-enforced ownership.
     */
    post: operations["markNotificationRead"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/integration-jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List integration job status
     * @description List integration job status. Roles: finance, platform_admin.
     */
    get: operations["listIntegrationJobs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/integration-jobs/{jobId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get integration job detail
     * @description Get integration job detail. Roles: finance, platform_admin.
     */
    get: operations["getIntegrationJob"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/webhooks/esign/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * E-Signature completion callback
     * @description Consumes inbound callback after HMAC signature and timestamp replay validation.
     */
    post: operations["handleEsignCallback"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    BoqLineItem: {
      /** Format: uuid */
      id?: string;
      quantity?: string;
      total?: components["schemas"]["Money"];
      unit?: string;
      unitRate?: components["schemas"]["Money"];
    };
    CollectionEnvelope: {
      data: Record<string, never>[];
      meta: components["schemas"]["ResponseMeta"];
    };
    CreateProjectRequest: {
      /** Format: uuid */
      clientUserId: string;
      /** Format: uuid */
      entityId: string;
      name: components["schemas"]["LocalizedText"];
      /** Format: date */
      startDate: string;
      /** Format: date */
      targetHandoverDate: string;
    };
    DocumentVersion: {
      clientShared?: boolean;
      /** Format: uuid */
      id?: string;
      /** @enum {string} */
      status?: "draft" | "for_review" | "approved" | "superseded";
      versionNo?: number;
    };
    Error: {
      error: {
        /** @enum {string} */
        code:
          | "VALIDATION_ERROR"
          | "UNAUTHENTICATED"
          | "FORBIDDEN"
          | "NOT_FOUND"
          | "CONFLICT"
          | "BUSINESS_RULE_VIOLATION"
          | "RATE_LIMITED"
          | "INTERNAL_ERROR";
        details?: {
          field?: string;
          issue?: string;
        }[];
        message: string;
        requestId: string;
      };
    };
    EsignCallback: {
      envelopeId: string;
      /** Format: date-time */
      signedAt: string;
      /** Format: uri */
      signedDocumentUrl: string;
      status: string;
    };
    /**
     * @example {
     *       "en": "Marina Tower Fit-Out",
     *       "ar": "تجهيز برج المارينا"
     *     }
     */
    LocalizedText: {
      [key: string]: string;
    };
    Money: {
      /** @description Decimal string, never a float */
      amount: string;
      currency: string;
    };
    Project: {
      /** Format: date-time */
      createdAt?: string;
      /** Format: uuid */
      entityId?: string;
      /** Format: uuid */
      id?: string;
      name?: components["schemas"]["LocalizedText"];
      /** Format: date */
      startDate?: string;
      /** @enum {string} */
      status?: "proposed" | "active" | "on_hold" | "handover_in_progress" | "closed" | "cancelled";
      /** Format: date */
      targetHandoverDate?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    ResponseMeta: {
      locale?: string;
      pagination?: {
        hasMore?: boolean;
        limit?: number;
        nextCursor?: string | null;
      };
      requestId?: string;
    };
    SignedUrl: {
      data: {
        /** Format: uri */
        downloadUrl: string;
        /** Format: date-time */
        expiresAt: string;
      };
    };
    SignedUpload: {
      data: {
        /** Format: date-time */
        expiresAt: string;
        /** Format: uri */
        uploadUrl: string;
        /** Format: uuid */
        versionId: string;
      };
    };
    SingleResourceEnvelope: {
      data: Record<string, never>;
      meta?: components["schemas"]["ResponseMeta"];
    };
  };
  responses: {
    /** @description Accepted for asynchronous processing. */
    Accepted: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["SingleResourceEnvelope"];
      };
    };
    /** @description Paginated BOQ line item collection. */
    BoqLineItemCollection: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["CollectionEnvelope"] & {
          data?: components["schemas"]["BoqLineItem"][];
        };
      };
    };
    /** @description Domain invariant or business rule failure. */
    BusinessRuleViolation: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Paginated collection response. */
    Collection: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["CollectionEnvelope"];
      };
    };
    /** @description State conflict or optimistic concurrency failure. */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Resource created. */
    Created: {
      headers: {
        Location?: string;
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["SingleResourceEnvelope"];
      };
    };
    /** @description DocumentVersion response. */
    DocumentVersion: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          data: components["schemas"]["DocumentVersion"];
          meta?: components["schemas"]["ResponseMeta"];
        };
      };
    };
    /** @description Paginated DocumentVersion collection. */
    DocumentVersionCollection: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["CollectionEnvelope"] & {
          data?: components["schemas"]["DocumentVersion"][];
        };
      };
    };
    /** @description Authenticated but categorically barred. */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Unexpected server error. */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Resource does not exist or caller is not authorized to know it exists. */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Project response. */
    Project: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          data: components["schemas"]["Project"];
          meta?: components["schemas"]["ResponseMeta"];
        };
      };
    };
    /** @description Rate limit exceeded. */
    RateLimited: {
      headers: {
        "Retry-After"?: string;
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Signed upload URL response. */
    SignedUpload: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["SignedUpload"];
      };
    };
    /** @description Signed download URL response. */
    SignedUrl: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["SignedUrl"];
      };
    };
    /** @description Successful response. */
    Success: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["SingleResourceEnvelope"];
      };
    };
    /** @description Missing, invalid, or expired JWT. */
    Unauthenticated: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Schema-level request validation failure. */
    ValidationError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    AssignmentId: string;
    BoqId: string;
    Cursor: string;
    EntityId: string;
    IdempotencyKey: string;
    IfMatch: string;
    Limit: number;
    MilestoneId: string;
    PackageId: string;
    ProjectId: string;
    RevisionId: string;
    Sort: string;
    UserId: string;
    VersionId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listProjects: {
    parameters: {
      query?: {
        limit?: components["parameters"]["Limit"];
        cursor?: components["parameters"]["Cursor"];
        sort?: components["parameters"]["Sort"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Collection"];
      401: components["responses"]["Unauthenticated"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  createProject: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateProjectRequest"];
      };
    };
    responses: {
      201: components["responses"]["Created"];
      400: components["responses"]["ValidationError"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      422: components["responses"]["BusinessRuleViolation"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  getProject: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: components["parameters"]["ProjectId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Project"];
      401: components["responses"]["Unauthenticated"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  updateProject: {
    parameters: {
      query?: never;
      header: {
        "If-Match": components["parameters"]["IfMatch"];
      };
      path: {
        projectId: components["parameters"]["ProjectId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Project"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  addProjectPhase: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        projectId: components["parameters"]["ProjectId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Created"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      422: components["responses"]["BusinessRuleViolation"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  addProjectMilestone: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        projectId: components["parameters"]["ProjectId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Created"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      422: components["responses"]["BusinessRuleViolation"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  markMilestoneClientVisible: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        projectId: components["parameters"]["ProjectId"];
        milestoneId: components["parameters"]["MilestoneId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Success"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      422: components["responses"]["BusinessRuleViolation"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  getProjectBoq: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: components["parameters"]["ProjectId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Success"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  createBoqRevision: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        boqId: components["parameters"]["BoqId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Created"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      422: components["responses"]["BusinessRuleViolation"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  listBoqLineItems: {
    parameters: {
      query?: {
        limit?: components["parameters"]["Limit"];
        cursor?: components["parameters"]["Cursor"];
      };
      header?: never;
      path: {
        boqId: components["parameters"]["BoqId"];
        revisionId: components["parameters"]["RevisionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["BoqLineItemCollection"];
      401: components["responses"]["Unauthenticated"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  addBoqLineItem: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        boqId: components["parameters"]["BoqId"];
        revisionId: components["parameters"]["RevisionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Created"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      422: components["responses"]["BusinessRuleViolation"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  submitBoqRevisionForApproval: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        boqId: components["parameters"]["BoqId"];
        revisionId: components["parameters"]["RevisionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Success"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  approveBoqRevision: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        boqId: components["parameters"]["BoqId"];
        revisionId: components["parameters"]["RevisionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      202: components["responses"]["Accepted"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  exportBoqRevisionPdf: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        boqId: components["parameters"]["BoqId"];
        revisionId: components["parameters"]["RevisionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["SignedUrl"];
      401: components["responses"]["Unauthenticated"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  createDocumentPackage: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        projectId: components["parameters"]["ProjectId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Created"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      422: components["responses"]["BusinessRuleViolation"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  listDocumentVersions: {
    parameters: {
      query?: {
        limit?: components["parameters"]["Limit"];
        cursor?: components["parameters"]["Cursor"];
      };
      header?: never;
      path: {
        packageId: components["parameters"]["PackageId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["DocumentVersionCollection"];
      401: components["responses"]["Unauthenticated"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  initiateDocumentVersionUpload: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        packageId: components["parameters"]["PackageId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["SignedUpload"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  completeDocumentVersionUpload: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        packageId: components["parameters"]["PackageId"];
        versionId: components["parameters"]["VersionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["DocumentVersion"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  submitDocumentVersionForReview: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        packageId: components["parameters"]["PackageId"];
        versionId: components["parameters"]["VersionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["DocumentVersion"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  approveDocumentVersion: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        packageId: components["parameters"]["PackageId"];
        versionId: components["parameters"]["VersionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["DocumentVersion"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  exportDocumentVersionPdf: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        packageId: components["parameters"]["PackageId"];
        versionId: components["parameters"]["VersionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["SignedUrl"];
      401: components["responses"]["Unauthenticated"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  getDocumentVersionDownloadUrl: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        packageId: components["parameters"]["PackageId"];
        versionId: components["parameters"]["VersionId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["SignedUrl"];
      401: components["responses"]["Unauthenticated"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  listUsers: {
    parameters: {
      query?: {
        limit?: components["parameters"]["Limit"];
        cursor?: components["parameters"]["Cursor"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Collection"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  provisionUser: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Created"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      422: components["responses"]["BusinessRuleViolation"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  updateUser: {
    parameters: {
      query?: never;
      header: {
        "If-Match": components["parameters"]["IfMatch"];
      };
      path: {
        userId: components["parameters"]["UserId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Success"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  listRoles: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Collection"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  assignUserRole: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        userId: components["parameters"]["UserId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Created"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      422: components["responses"]["BusinessRuleViolation"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  revokeUserRoleAssignment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: components["parameters"]["UserId"];
        assignmentId: components["parameters"]["AssignmentId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful deactivate/revoke response with no body. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  listEntities: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Collection"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  provisionEntity: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      201: components["responses"]["Created"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      422: components["responses"]["BusinessRuleViolation"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  updateEntity: {
    parameters: {
      query?: never;
      header: {
        "If-Match": components["parameters"]["IfMatch"];
      };
      path: {
        entityId: components["parameters"]["EntityId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Success"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  reassignProjectEntity: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        projectId: components["parameters"]["ProjectId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Success"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      422: components["responses"]["BusinessRuleViolation"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  getPortfolioDashboard: {
    parameters: {
      query?: {
        blend?: boolean;
        asOf?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Success"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  listNotifications: {
    parameters: {
      query?: {
        limit?: components["parameters"]["Limit"];
        cursor?: components["parameters"]["Cursor"];
        status?: "unread" | "read";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Collection"];
      401: components["responses"]["Unauthenticated"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  markNotificationRead: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": components["parameters"]["IdempotencyKey"];
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Success"];
      401: components["responses"]["Unauthenticated"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  listIntegrationJobs: {
    parameters: {
      query?: {
        limit?: components["parameters"]["Limit"];
        cursor?: components["parameters"]["Cursor"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Collection"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  getIntegrationJob: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        jobId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["Success"];
      401: components["responses"]["Unauthenticated"];
      403: components["responses"]["Forbidden"];
      404: components["responses"]["NotFound"];
      429: components["responses"]["RateLimited"];
      500: components["responses"]["InternalError"];
    };
  };
  handleEsignCallback: {
    parameters: {
      query?: never;
      header: {
        "X-Signature": string;
        "X-Timestamp": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EsignCallback"];
      };
    };
    responses: {
      200: components["responses"]["Success"];
      401: components["responses"]["Unauthenticated"];
      409: components["responses"]["Conflict"];
      500: components["responses"]["InternalError"];
    };
  };
}
